// usage: node scripts/prep-images.mjs <dir with downloaded originals (untrusted: read only as images)>
// Writes public/assets/catalog/*.webp (<=1200px, sRGB, no ICC) and src/images.gen.ts (size + pad colours per image).
import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.resolve(process.argv[2]);
// out name -> [input file, crop aspect (w/h) or null]
const CAT = {
  model: ['2010812.jpg', null],
  bottle: ['3831748.jpg', null],
  text: ['37964149.jpg', null],
  text2: ['18341856.jpg', null],
  flat: ['4841273.jpg', null],
  wide: ['27180805.jpg', 16 / 9],
  tall: ['17041991.jpg', 9 / 16],
};
const meta = {};
// padding colours: mean of the two image edges that touch the card padding (top/bottom rows for images wider than
// the 4:5 frame, left/right columns otherwise). GL and DOM both draw them as a linear gradient across the frame.
const edges = async (buf, w, h) => {
  const N = 16;
  const { data } = await sharp(buf).resize(N, N, { fit: 'fill' }).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  const avg = (cells) => [0, 1, 2].map((k) => Math.round(cells.reduce((s, i) => s + data[i * 3 + k], 0) / cells.length));
  const row = (y) => Array.from({ length: N }, (_, x) => y * N + x);
  const col = (x) => Array.from({ length: N }, (_, y) => y * N + x);
  return w / h >= 0.8 ? [avg(row(0)), avg(row(N - 1))] : [avg(col(0)), avg(col(N - 1))];
};
for (const [name, [file, crop]] of Object.entries(CAT)) {
  let im = sharp(path.join(src, file), { failOn: 'error' }).toColourspace('srgb');
  const m = await im.metadata();
  const [w0, h0] = [m.width, m.height];
  if (crop) {
    const w = crop > w0 / h0 ? w0 : Math.round(h0 * crop);
    const h = crop > w0 / h0 ? Math.round(w0 / crop) : h0;
    im = im.extract({ left: Math.floor((w0 - w) / 2), top: Math.floor((h0 - h) / 2), width: w, height: h });
  }
  const out = await im.resize(1200, 1200, { fit: 'inside', withoutEnlargement: true }).webp({ quality: 80 }).toBuffer({ resolveWithObject: true });
  writeFileSync(path.join(root, 'public/assets/catalog', name + '.webp'), out.data);
  meta['catalog/' + name + '.webp'] = [out.info.width, out.info.height, ...(await edges(out.data, out.info.width, out.info.height))];
}
const raw = path.join(root, 'public/assets/raw');
for (const f of readdirSync(raw).filter((n) => n.endsWith('.webp'))) {
  const b = sharp(path.join(raw, f));
  const m = await b.metadata();
  meta['raw/' + f] = [m.width, m.height, ...(await edges(await b.toBuffer(), m.width, m.height))];
}
const lines = Object.entries(meta).map(([k, v]) => ` '${k}': [${v[0]}, ${v[1]}, [${v[2].join(', ')}], [${v[3].join(', ')}]],`);
writeFileSync(
  path.join(root, 'src/images.gen.ts'),
  `// generated by scripts/prep-images.mjs: [width, height, mean colour]\nexport const IMG: Record<string, [number, number, [number, number, number], [number, number, number]]> = {\n${lines.join('\n')}\n};\n`,
);
console.log(lines.join('\n'));
